// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Internal-1]
	_ = x[System-2]
	_ = x[Unauthorized-3]
	_ = x[Forbidden-4]
	_ = x[InvalidInput-5]
	_ = x[Conflict-6]
	_ = x[NotFound-7]
	_ = x[ExecutionFailed-8]
	_ = x[ParsingFailed-9]
	_ = x[Timeout-10]
	_ = x[Unavailable-11]
}

const _ErrorType_name = "UnknownInternalSystemUnauthorizedForbiddenInvalidInputConflictNotFoundExecutionFailedParsingFailedTimeoutUnavailable"

var _ErrorType_index = [...]uint8{0, 7, 15, 21, 33, 42, 54, 62, 70, 85, 98, 105, 116}

func (i ErrorType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErrorType_index)-1 {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[idx]:_ErrorType_index[idx+1]]
}
